
version: "3.9"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - ./mssql/data:/var/opt/mssql
      - ./import:/var/opt/mssql/import

  db-init:
    image: mcr.microsoft.com/mssql-tools:latest
    depends_on:
      - sqlserver
    environment:
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    volumes:
      - ./sql:/sql
      - ./import:/var/opt/mssql/import
      - ./generated:/generated
    entrypoint: ["/bin/bash","/sql/init.sh"]
